/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package saboryartealcarbon;
import javax.swing.ImageIcon;
import java.awt.Image;
import java.io.File;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.io.FileNotFoundException;
import java.io.RandomAccessFile;
/**
 *
 * @author simon
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        setTitle("Principal");
        setSize(350,490);
        setLocationRelativeTo(null);
        setResizable(false);
        ImageIcon imagemain=new
        ImageIcon("images\\main.jpg");
        Image originalimage=imagemain.getImage();
        Image scaled_image=originalimage.getScaledInstance(350,300,Image.SCALE_SMOOTH);
        ImageIcon scaledIcon=new ImageIcon(scaled_image);
        mainimage.setIcon(scaledIcon);
        mainimage.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Facturarbtn = new javax.swing.JButton();
        Rendimientobtn = new javax.swing.JButton();
        mainimage = new javax.swing.JLabel();
        txtAD = new javax.swing.JTextField();
        ADbtn = new javax.swing.JButton();
        foldergbtn = new javax.swing.JButton();
        foldergtxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Facturarbtn.setText("Facturar");
        Facturarbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FacturarbtnActionPerformed(evt);
            }
        });

        Rendimientobtn.setText("Rendimiento");
        Rendimientobtn.setAlignmentY(0.0F);
        Rendimientobtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RendimientobtnActionPerformed(evt);
            }
        });

        txtAD.setText("Path Datos");
        txtAD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtADActionPerformed(evt);
            }
        });

        ADbtn.setText("Actualizar Datos");
        ADbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADbtnActionPerformed(evt);
            }
        });

        foldergbtn.setText("Carpeta guardar");
        foldergbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foldergbtnActionPerformed(evt);
            }
        });

        foldergtxt.setText("Carpeta guardar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainimage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAD, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Facturarbtn)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(foldergtxt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(foldergbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Rendimientobtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ADbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(mainimage, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Facturarbtn)
                    .addComponent(Rendimientobtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ADbtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(foldergbtn)
                    .addComponent(foldergtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FacturarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FacturarbtnActionPerformed
        // TODO add your handling code here:
        
        //se pone visible una nueva ventana en la cual se va a realizar la facturacion
        Facturar ventanafacturar= new Facturar();
        ventanafacturar.setVisible(true);
        //ocultar ventana principal
        this.dispose();
        
        
    }//GEN-LAST:event_FacturarbtnActionPerformed

    private void RendimientobtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RendimientobtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RendimientobtnActionPerformed

    private void ADbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADbtnActionPerformed
        // TODO add your handling code here:
        // la idea de este boton es cambiar el path de donde se sacan los datos de los 
        //productos
        //por defecto viene con unos datos en la carpeta datos
        
        //se llama a la clase LyAfile que lee y actualiza el archivo links

            LyAfile l=new LyAfile(txtAD.getText(),"DATOS");
  
       
        
        
    }//GEN-LAST:event_ADbtnActionPerformed

    private void txtADActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtADActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtADActionPerformed

    private void foldergbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foldergbtnActionPerformed
        // TODO add your handling code here:
        //cambiar el path donde se van a guardar los datos
        //de facturacion del dia
        //se llama a la clase LyAfile que lee y actualiza el archivo links
        LyAfile l=new LyAfile(foldergtxt.getText(),"foldersave");
    }//GEN-LAST:event_foldergbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Principal ventanaprincipal=new Principal();
                ventanaprincipal.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ADbtn;
    private javax.swing.JButton Facturarbtn;
    private javax.swing.JButton Rendimientobtn;
    private javax.swing.JButton foldergbtn;
    private javax.swing.JTextField foldergtxt;
    private javax.swing.JLabel mainimage;
    private javax.swing.JTextField txtAD;
    // End of variables declaration//GEN-END:variables

}
